[project]
name = "ais-dev2il-ais-power-smoothie-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyjokes>=0.8.3",
    "rich>=14.3.2",
]
